import sys
from scripts.git_manager import GitManager

def submit_for_review_tool(git_manager: GitManager, task_id: int, task_title: str) -> str:
    """
    A tool to commit all current changes and create a pull request.
    This should be the final step in any successful plan.
    """
    if not isinstance(task_id, int) or not isinstance(task_title, str):
        return "HALT: Invalid arguments for submit_for_review. task_id must be an int, task_title must be a string."

    commit_message = f"feat(task-{task_id}): {task_title}"
    pr_title = f"[Task {task_id}] {task_title}"
    pr_body = f"Completes Task {task_id}: {task_title}\n\nThis PR was automatically generated by the autonomous agent."

    print(f"Attempting to commit and push with message: '{commit_message}'")
    if not git_manager.commit_and_push(commit_message):
        error_message = "HALT: Failed to commit and push changes. There might be no changes to commit, or there could be a git configuration issue."
        print(error_message, file=sys.stderr)
        return error_message

    print(f"Attempting to create pull request with title: '{pr_title}'")
    if not git_manager.create_pull_request(title=pr_title, body=pr_body):
        error_message = "HALT: Failed to create pull request. Ensure 'gh' CLI is installed, authenticated, and has 'repo' and 'workflow' scopes."
        print(error_message, file=sys.stderr)
        return error_message

    success_message = f"Successfully submitted task {task_id} for review."
    print(success_message)
    return success_message
